security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders: 
        App\Entity\User:
            algorithm: bcrypt
    
    providers:
        users_in_memory: { memory: null }
        user_in_database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            
            provider: user_in_database

            form_login:
                login_path: user_login
                check_path: user_login

            logout:
                path: user_logout
                target: homepage

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clients, roles: ROLE_USER }
        - { path: ^/lieux, roles: ROLE_USER }
        - { path: ^/rendez-vous, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
