<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.form' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRendererInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRenderer.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRendererEngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractRendererEngine.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/Templating/TemplatingRendererEngine.php';

return $this->privates['templating.helper.form'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper(new \Symfony\Component\Form\FormRenderer(new \Symfony\Component\Form\Extension\Templating\TemplatingRendererEngine(($this->privates['templating.engine.php'] ?? $this->load('getTemplating_Engine_PhpService.php')), $this->parameters['templating.helper.form.resources']), ($this->services['security.csrf.token_manager'] ?? $this->load('getSecurity_Csrf_TokenManagerService.php'))));
