<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.logout_url' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-bundle/Templating/Helper/LogoutUrlHelper.php';

return $this->privates['templating.helper.logout_url'] = new \Symfony\Bundle\SecurityBundle\Templating\Helper\LogoutUrlHelper(($this->privates['security.logout_url_generator'] ?? $this->getSecurity_LogoutUrlGeneratorService()));
