<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fLo94d.' shared service.

return $this->privates['.service_locator.fLo94d.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'appointment' => ['privates', '.errored..service_locator.fLo94d..App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.fLo94d.": it references class "App\\Entity\\Appointment" but no such service exists.'],
]);
