<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AppointmentController::delete' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\AppointmentController::edit' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\AppointmentController::index' => ['privates', '.service_locator.no9llaW', 'get_ServiceLocator_No9llaWService.php', true],
    'App\\Controller\\AppointmentController::show' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\CustomerController::delete' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\CustomerController::edit' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\CustomerController::index' => ['privates', '.service_locator.itO3VKs', 'get_ServiceLocator_ItO3VKsService.php', true],
    'App\\Controller\\CustomerController::show' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\PlaceController::delete' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\PlaceController::edit' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\PlaceController::index' => ['privates', '.service_locator.ArQG4l0', 'get_ServiceLocator_ArQG4l0Service.php', true],
    'App\\Controller\\PlaceController::show' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\AppointmentController:delete' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\AppointmentController:edit' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\AppointmentController:index' => ['privates', '.service_locator.no9llaW', 'get_ServiceLocator_No9llaWService.php', true],
    'App\\Controller\\AppointmentController:show' => ['privates', '.service_locator.fLo94d.', 'get_ServiceLocator_FLo94d_Service.php', true],
    'App\\Controller\\CustomerController:delete' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\CustomerController:edit' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\CustomerController:index' => ['privates', '.service_locator.itO3VKs', 'get_ServiceLocator_ItO3VKsService.php', true],
    'App\\Controller\\CustomerController:show' => ['privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true],
    'App\\Controller\\PlaceController:delete' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\PlaceController:edit' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\PlaceController:index' => ['privates', '.service_locator.ArQG4l0', 'get_ServiceLocator_ArQG4l0Service.php', true],
    'App\\Controller\\PlaceController:show' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
