<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMRuFNUc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMRuFNUc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMRuFNUc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMRuFNUc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMRuFNUc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MRuFNUc',
    'container.build_id' => '4efc6a6a',
    'container.build_time' => 1554073200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMRuFNUc');
