<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Rau1Rn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Rau1Rn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Rau1Rn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Rau1Rn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7Rau1Rn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7Rau1Rn',
    'container.build_id' => '119165c3',
    'container.build_time' => 1583888991,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Rau1Rn');
