<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'appointments' => [[], ['_controller' => 'App\\Controller\\AppointmentController::index'], [], [['text', '/rendez-vous']], [], []],
    'appointment_edit' => [['id'], ['_controller' => 'App\\Controller\\AppointmentController::edit_appointment'], [], [['text', '/modification'], ['variable', '/', '[^/]++', 'id'], ['text', '/rendez-vous']], [], []],
    'appointment_delete' => [['id'], ['_controller' => 'App\\Controller\\AppointmentController::appointment_delete'], [], [['text', '/supression'], ['variable', '/', '[^/]++', 'id'], ['text', '/rendez-vous']], [], []],
    'customers' => [[], ['_controller' => 'App\\Controller\\CustomerController::index'], [], [['text', '/clients']], [], []],
    'customer_edit' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::edit_customer'], [], [['text', '/modification'], ['variable', '/', '[^/]++', 'id'], ['text', '/clients']], [], []],
    'customer_delete' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::customer_delete'], [], [['text', '/supression'], ['variable', '/', '[^/]++', 'id'], ['text', '/clients']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\HomeController::dashboard'], [], [['text', '/dashbord']], [], []],
    'places' => [[], ['_controller' => 'App\\Controller\\PlaceController::index'], [], [['text', '/lieux']], [], []],
    'user_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/connexion']], [], []],
    'user_logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/deconnexion']], [], []],
    'registration' => [[], ['_controller' => 'App\\Controller\\UserController::registration'], [], [['text', '/inscription']], [], []],
];
