<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ViwMQSq' shared service.

return $this->privates['.service_locator.ViwMQSq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'customer' => ['privates', '.errored..service_locator.ViwMQSq.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.ViwMQSq": it references class "App\\Entity\\Customer" but no such service exists.'],
]);
